-- =====================================================
-- DESPENSA COMPARADOR - SCHEMA COMPLETO
-- Ejecutar en Supabase SQL Editor
-- =====================================================

-- Eliminar tablas si existen (para limpiar, comentar si no quieres)
DROP TABLE IF EXISTS prices CASCADE;
DROP TABLE IF EXISTS unit_suggestions CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS providers CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS roles CASCADE;

-- Crear tablas
CREATE TABLE roles (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role_id BIGINT REFERENCES roles(id),
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE providers (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT UNIQUE NOT NULL,
  whatsapp TEXT,
  email TEXT,
  website TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE categories (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE products (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  brand TEXT NOT NULL,
  category_id BIGINT REFERENCES categories(id),
  unit TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(name, brand)
);

CREATE TABLE prices (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
  provider_id BIGINT REFERENCES providers(id) ON DELETE CASCADE,
  price DECIMAL(10,2) NOT NULL,
  updated_at TIMESTAMP DEFAULT NOW(),
  updated_by UUID REFERENCES users(id)
);

CREATE TABLE unit_suggestions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_name TEXT NOT NULL,
  brand TEXT,
  suggested_unit TEXT NOT NULL,
  times_used INT DEFAULT 1,
  UNIQUE(product_name, brand)
);

-- Insertar roles base
INSERT INTO roles (name) VALUES ('admin'), ('gerente'), ('cajero')
ON CONFLICT (name) DO NOTHING;

-- Insertar usuario admin (contraseña: Mutante123?)
INSERT INTO users (email, password, role_id) 
VALUES ('admin@despensa.com', 'Mutante123?', (SELECT id FROM roles WHERE name='admin'))
ON CONFLICT (email) DO NOTHING;

-- Insertar categorías de ejemplo
INSERT INTO categories (name) VALUES 
('Comestible'), 
('Bebida'), 
('Fiambre'), 
('Limpieza'), 
('Frutas y Verduras'),
('Lácteos'),
('Panadería')
ON CONFLICT (name) DO NOTHING;

-- Insertar proveedores de ejemplo
INSERT INTO providers (name, whatsapp, email, website) VALUES 
('Distribuidora El Progreso', '011-1234-5678', 'ventas@elprogreso.com', 'https://elprogreso.com'),
('Proveedor Mayorista SA', '011-8765-4321', 'info@mayorista.com', NULL),
('Almacén Central', '011-1122-3344', NULL, NULL)
ON CONFLICT (name) DO NOTHING;

-- Insertar productos de ejemplo
INSERT INTO products (name, brand, category_id, unit) VALUES 
('Arroz', 'Molino Ala', (SELECT id FROM categories WHERE name='Comestible'), 'kg'),
('Arroz', 'Gallo', (SELECT id FROM categories WHERE name='Comestible'), 'kg'),
('Leche', 'La Serenísima', (SELECT id FROM categories WHERE name='Lácteos'), 'litros'),
('Gaseosa', 'Coca Cola', (SELECT id FROM categories WHERE name='Bebida'), 'litros'),
('Pan', 'Fargo', (SELECT id FROM categories WHERE name='Panadería'), 'unidades')
ON CONFLICT (name, brand) DO NOTHING;

-- Insertar precios de ejemplo
INSERT INTO prices (product_id, provider_id, price, updated_by) 
SELECT p.id, pr.id, 
  CASE 
    WHEN p.brand = 'Molino Ala' THEN 1200
    WHEN p.brand = 'Gallo' THEN 1150
    WHEN p.brand = 'La Serenísima' THEN 850
    WHEN p.brand = 'Coca Cola' THEN 950
    ELSE 500
  END,
  (SELECT id FROM users WHERE email='admin@despensa.com')
FROM products p, providers pr
WHERE NOT EXISTS (
  SELECT 1 FROM prices WHERE product_id = p.id AND provider_id = pr.id
)
LIMIT 10;

-- Crear índices para mejorar rendimiento
CREATE INDEX IF NOT EXISTS idx_products_name ON products(name);
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category_id);
CREATE INDEX IF NOT EXISTS idx_prices_product ON prices(product_id);
CREATE INDEX IF NOT EXISTS idx_prices_provider ON prices(provider_id);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

-- Verificar datos insertados
SELECT 'Roles:' as tabla, COUNT(*) as cantidad FROM roles
UNION ALL
SELECT 'Usuarios:', COUNT(*) FROM users
UNION ALL
SELECT 'Categorías:', COUNT(*) FROM categories
UNION ALL
SELECT 'Proveedores:', COUNT(*) FROM providers
UNION ALL
SELECT 'Productos:', COUNT(*) FROM products
UNION ALL
SELECT 'Precios:', COUNT(*) FROM prices;